apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: le999/server:1.0
        ports:
        - containerPort: 3000
        env:
          - name: RETHINK_HOST
            value: rethinkdb1-rethinkdb-proxy          
          - name: RETHINK_PORT
            value: 28015   
          - name: RETHINK_PASSWORD
            value: rethinkdb   
          - name: RETHINK_USER
            value: admin

          - name: PORT
            value: "3000"
          - name: MONGO_URI
            value: mongodb://root:example@mongodb1:27017/mydb
          - name: KAFKA_URL
            value: kafka-release-0.kafka-release-headless.default.svc.cluster.local:9092
          - name: SAWTOOTH_VALIDATOR_URL
            value: tcp://sawtooth-0:4004
          - name: SAWTOOTH_REST_API_URL
            value: http://sawtooth-0:8008
          - name: BACK_URL
            value: http://localhost:3000/api/
          - name: PUBLIC_KEY
            value: "-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDCUDXMn4PVqdm2V7QTEcanuPFY\nn8OMxM4jDGiByYjTjoBp+YIvJLciIyUgTltPcpGKutxUgwzMfuJ+uqAoGOkI6DWl\nIJwhbN0DCcEr/vI+LTo5L0XUF95I31mPa43hPpmjatAH76lOMW9VVI3iKrsKBLVS\nnXZxvqN64gECS0ACYQIDAQAB\n-----END PUBLIC KEY-----"
          - name: PRIVATE_KEY
            value: "-----BEGIN RSA PRIVATE KEY-----\nMIICXQIBAAKBgQDCUDXMn4PVqdm2V7QTEcanuPFYn8OMxM4jDGiByYjTjoBp+YIv\nJLciIyUgTltPcpGKutxUgwzMfuJ+uqAoGOkI6DWlIJwhbN0DCcEr/vI+LTo5L0XU\nF95I31mPa43hPpmjatAH76lOMW9VVI3iKrsKBLVSnXZxvqN64gECS0ACYQIDAQAB\nAoGARLKa8qcKswWDxSWosn08YJvQJ+cD+cayok2GvSwFRdZBrDXcQtKWNGl8fLl3\nKtV0gzmhH/fdFIdfiDJu4P49lJvIi4uOxYdWYsUdx3j9Kapg5D6MDSxTOu+hr/at\nmxuLkDz5mwsw7N6J12m4oXsrTMq4Z6kX7lkt74o2tpLLICkCQQD61vW3FFqMO1CO\n5F9X5k8L48CVGRURLmNUsGYcy0RncY3MkBp0lcWygm90yF6oEICbS9HjDSmGDRtT\nKybruWWbAkEAxk+OSXD1z7pbWtZL1mUGLtr2CLm7SZgPwrF5eTbexEzKdV75eI65\n7xWrHx/sbobT26/3up1ZnyORkCLnAHzVswJBAKUSAPFSO6Q9BG6Eaxn1Pd+dKYb0\n0qBT3ppE223ndkR8vcv4qPA//7HRlHdNxLzk3z1TT/QTHVhSF8FLjHljsDECQQCZ\n2DoQK3vnDTG2BK2Mw47KZr+cAUqUS01ewwPzz2d+bfxalbV/m2oPWoYIfWGUVTCi\nK59JvKw8UwGoCgufSzkVAkBpiI6xBM1k/QQWn2VvRS+FOiFYPcorbdrT+y3N4/PD\naam5oawrOKhBhVEE9j9GkRRa/Z+LM2ZM72XCyVAwqlsW\n-----END RSA PRIVATE KEY-----"
---

apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: ClusterIP
  selector:
    app: myapp 
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: myapp-lb
spec:
  selector:
    app: myapp
  type: LoadBalancer
  ports:
    - name: "3000"
      port: 3000
      nodePort: 30001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: ledger-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledger-sync
  template:
    metadata:
      labels:
        app: ledger-sync
    spec:
      containers:
      - name: ledger-sync
        image: le999/ledger_sync:1.0
        env:
          - name: RETHINK_HOST
            value: rethinkdb1-rethinkdb-proxy          
          - name: RETHINK_PORT
            value: 28015   
          - name: RETHINK_PASSWORD
            value: rethinkdb   
          - name: RETHINK_USER
            value: admin

          # - name: PORT
          #   value: "3000"
          # - name: MONGO_URI
          #   value: mongodb://root:example@mongodb1:27017/mydb
          # - name: KAFKA_URL
          #   value: kafka-release-0.kafka-release-headless.default.svc.cluster.local:9092
          # - name: SAWTOOTH_VALIDATOR_URL
          #   value: tcp://sawtooth-0:4004
          # - name: SAWTOOTH_REST_API_URL
          #   value: http://sawtooth-0:8008
          # - name: BACK_URL
          #   value: http://localhost:3000/api/
          # - name: PUBLIC_KEY
          #   value: "-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDCUDXMn4PVqdm2V7QTEcanuPFY\nn8OMxM4jDGiByYjTjoBp+YIvJLciIyUgTltPcpGKutxUgwzMfuJ+uqAoGOkI6DWl\nIJwhbN0DCcEr/vI+LTo5L0XUF95I31mPa43hPpmjatAH76lOMW9VVI3iKrsKBLVS\nnXZxvqN64gECS0ACYQIDAQAB\n-----END PUBLIC KEY-----"
          # - name: PRIVATE_KEY
          #   value: "-----BEGIN RSA PRIVATE KEY-----\nMIICXQIBAAKBgQDCUDXMn4PVqdm2V7QTEcanuPFYn8OMxM4jDGiByYjTjoBp+YIv\nJLciIyUgTltPcpGKutxUgwzMfuJ+uqAoGOkI6DWlIJwhbN0DCcEr/vI+LTo5L0XU\nF95I31mPa43hPpmjatAH76lOMW9VVI3iKrsKBLVSnXZxvqN64gECS0ACYQIDAQAB\nAoGARLKa8qcKswWDxSWosn08YJvQJ+cD+cayok2GvSwFRdZBrDXcQtKWNGl8fLl3\nKtV0gzmhH/fdFIdfiDJu4P49lJvIi4uOxYdWYsUdx3j9Kapg5D6MDSxTOu+hr/at\nmxuLkDz5mwsw7N6J12m4oXsrTMq4Z6kX7lkt74o2tpLLICkCQQD61vW3FFqMO1CO\n5F9X5k8L48CVGRURLmNUsGYcy0RncY3MkBp0lcWygm90yF6oEICbS9HjDSmGDRtT\nKybruWWbAkEAxk+OSXD1z7pbWtZL1mUGLtr2CLm7SZgPwrF5eTbexEzKdV75eI65\n7xWrHx/sbobT26/3up1ZnyORkCLnAHzVswJBAKUSAPFSO6Q9BG6Eaxn1Pd+dKYb0\n0qBT3ppE223ndkR8vcv4qPA//7HRlHdNxLzk3z1TT/QTHVhSF8FLjHljsDECQQCZ\n2DoQK3vnDTG2BK2Mw47KZr+cAUqUS01ewwPzz2d+bfxalbV/m2oPWoYIfWGUVTCi\nK59JvKw8UwGoCgufSzkVAkBpiI6xBM1k/QQWn2VvRS+FOiFYPcorbdrT+y3N4/PD\naam5oawrOKhBhVEE9j9GkRRa/Z+LM2ZM72XCyVAwqlsW\n-----END RSA PRIVATE KEY-----"
